import{a as S,S as E,i as l}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const q="36675717-03e407770521c85c00994a8a5",v="https://pixabay.com/api/";async function m(o,t){try{const s=await S.get(v,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:t}});return{images:s.data.hits,total:s.data.totalHits}}catch(s){return console.error("Error fetching images:",s),{images:[],total:0}}}let P=new E(".gallery a");function f(o,t=!1){const s=document.querySelector(".gallery"),n=o.map(({webformatURL:e,largeImageURL:r,tags:i,likes:h,views:b,comments:w,downloads:L})=>`
    <a href="${r}" class="gallery-item">
      <img src="${e}" alt="${i}" />
      <div class="info">
        <p>Likes ${h}</p>
        <p>Views ${b}</p>
        <p>Comments ${w}</p>
        <p>Downloads ${L}</p>
      </div>
    </a>`).join("");t?s.insertAdjacentHTML("beforeend",n):s.innerHTML=n,P.refresh()}const $=document.querySelector("#search-form"),g=document.querySelector(".gallery"),y=document.querySelector(".loader"),a=document.querySelector("#load-more");let d="",c=1;const p=40;let u=0;$.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.target.elements.searchQuery.value.trim(),!d){l.warning({title:"Warning",message:"Please enter a search query!"});return}c=1,g.innerHTML="",a.style.display="none",y.style.display="block";try{const{images:t,total:s}=await m(d,c);if(u=s,y.style.display="none",t.length===0){l.error({title:"Error",message:"Sorry, no images found. Try again!"});return}f(t),u>p&&(a.style.display="block")}catch(t){console.error(t),l.error({title:"Error",message:"Something went wrong. Please try again later."})}});a.addEventListener("click",async()=>{c++,a.style.display="none",y.style.display="block";try{const{images:o}=await m(d,c);f(o,!0),y.style.display="none";const{height:t}=g.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),c*p>=u?(a.style.display="none",l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})):a.style.display="block"}catch(o){console.error(o),l.error({title:"Error",message:"Something went wrong. Please try again later."})}});
//# sourceMappingURL=index.js.map
